  
 -- You have been hired as a data analyst for a small startup that sells organic fruits and vegetables. 
 -- Your task is to analyze the sales data from the past year and
 -- identify the top-selling products and the most profitable regions.
 -- You need to use SQL to query the data stored in a database to do this.
 
 -- Task 1: Create the 'sales_data' table in the database using 
 -- the above SQL command. Keep the following columns inside the table 
 -- i.e: product_name, region, sales_date, units_sold, revenue.
 -- to create a table we use create table command as follows
 CREATE TABLE sales_data101 (
    product_name VARCHAR(50),
    region VARCHAR(50),
    sales_date DATE,
    units_sold INT,
    revenue FLOAT
);


-- Task 2: Insert the data into the 'sales_data' table:
-- to insert a data into any table we use intsert into statement as follows
INSERT INTO sales_data101 (product_name, region, sales_date, units_sold, revenue) 
VALUES 
('Organic Apples', 'North', '2022-01-01', 100, 2000.00),
('Organic Bananas', 'North', '2022-01-01', 150, 3000.00),
('Organic Apples', 'South', '2022-01-01', 50, 1000.00),
('Organic Bananas', 'South', '2022-01-01', 200, 4000.00),
('Organic Apples', 'North', '2022-02-01', 75, 1500.00),
('Organic Bananas', 'North', '2022-02-01', 125, 2500.00),
('Organic Apples', 'South', '2022-02-01', 25, 500.00),
('Organic Bananas', 'South', '2022-02-01', 175, 3500.00);


-- Task 3: Find the total revenue generated by the company. 
--  to find the total revenue of the company first we need to view the details 
-- by using select command

select*from sales_data101

-- revenue will be equal to (units_solds*revenue)
select product_name,sum(revenue)
from sales_data101
group by product_name   
-- >>revenue generated by each product
select sum(revenue)
from sales_data101


-- Task 4: Find the total number of units sold.
-- to find the total no of unit sold we need to sum the no unit sold
select sum(units_sold)
from sales_data101

-- Task 5: Find the total revenue generated by product. 
select product_name,sum(revenue)
from sales_data101
group by product_name

