select*from sales_data

-- Find the total revenue generated by the company
select sum(revenue) as total_revenue from 
sales_data

-- revenue by each product
select product_name ,sum(revenue) as revenue_by_each_product
from sales_data
group by product_name

-- Find the total number of units sold
select sum(units_sold)  from sales_data
-- units solds from each product
select product_name ,sum(units_sold) from sales_data
group by product_name
order by product_name desc

--  Find the total revenue generated by product
select product_name , sum(revenue) as total_revenue
from sales_data
group by
product_name



